django-2-modules-example/urls.py
# -*- coding: utf-8 -*-
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('start.urls')),
    path('users', include('users.urls')),
    path('projects', include('projects.urls')),
]

projects/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from projects import views
app_name = 'projects'


urlpatterns = [
    path('', views.Index.as_view(), name='index'),
]

start/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from start import views
app_name = 'start'


urlpatterns = [
    path('', views.Index.as_view(), name='index'),
]

users/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from users import views
app_name = 'users'


urlpatterns = [
    path('', views.Index.as_view(), name='index'),
]

base/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models

# Create your models here.

start/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render

# Create your views here.

projects/views.py
# -*- coding: utf-8 -*-
from django.views.generic import TemplateView


class Index(TemplateView):
    """
    Class that shows the index template of the projects module.
    """
    template_name = "projects/index.html"

start/views.py
# -*- coding: utf-8 -*-
from django.views.generic import TemplateView


class Index(TemplateView):
    """
    Class that shows the index template of the start module.
    """
    template_name = "start/index.html"

users/views.py
# -*- coding: utf-8 -*-
from django.views.generic import TemplateView


class Index(TemplateView):
    """
    Class that shows the index template of the users module.
    """
    template_name = "users/index.html"

base/templates/base/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Base{% endblock %}</title>
</head>
<body>
  <a href="{% url 'start:index' %}">Start module</a> | <a href="{% url 'users:index' %}">Users module</a> | <a href="{% url 'projects:index' %}">Projects module</a>
  {% block body %}
    Base
  {% endblock %}
  </body>
</html>

projects/templates/projects/index.html
{% extends "base/base.html" %}
{% block title %}Projects module{% endblock %}
{% block body %}
  <h2>Hello! this is the index template of the projects module.</h2>
{% endblock %}

start/templates/start/index.html
{% extends "base/base.html" %}
{% block title %}Start module{% endblock %}
{% block body %}
  <h2>Hello! this is the index template of the start module.</h2>
{% endblock %}

users/templates/users/index.html
{% extends "base/base.html" %}
{% block title %}Users module{% endblock %}
{% block body %}
  <h2>Hello! this is the index template of the users module.</h2>
{% endblock %}